### ISSUE TITLE
Implement basic LO QCD solution

### ISSUE THREAD

**Issue by scarrazza** [N3PDF/eko#5]
Steps:
- [x] encode the LO splitting functions
- [x] implement the beta function
- [x] maintain the `alphas` running fixed for the time being
- [x] solve the linear system algebra for the singlet and non-singlet sectors in N space
- [x] construct the final kernel operator in N space
- [x] invert the kernel to x space
- [x] benchmark results against APFEL

**Comment by felixhekhorn** [comment]
benchmark will be start implemented in #59
